package trabteoria;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cc151255911
 */
public class iu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form iu_Principal
     */
    public iu_Principal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        entradaA = new javax.swing.JTextField();
        entradaB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        optSoma = new javax.swing.JRadioButton();
        optSomaP = new javax.swing.JRadioButton();
        optSub = new javax.swing.JRadioButton();
        optAB = new javax.swing.JRadioButton();
        optAiB = new javax.swing.JRadioButton();
        optPrimo = new javax.swing.JRadioButton();
        optFatorial = new javax.swing.JRadioButton();
        optPoten = new javax.swing.JRadioButton();
        optResto = new javax.swing.JRadioButton();
        optBtoA = new javax.swing.JRadioButton();
        optZerar = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regA = new javax.swing.JLabel();
        regB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        resultadoReg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        entradaA.setText("0");
        entradaA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaAFocusLost(evt);
            }
        });
        entradaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaAActionPerformed(evt);
            }
        });

        entradaB.setText("0");
        entradaB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                entradaBFocusLost(evt);
            }
        });

        jLabel1.setText("A:");

        jLabel2.setText("B:");

        jLabel3.setText("Resultado:");

        resultado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        buttonGroup1.add(optSoma);
        optSoma.setText("Soma");

        buttonGroup1.add(optSomaP);
        optSomaP.setText("Soma Preservando");

        buttonGroup1.add(optSub);
        optSub.setText("Subtração");

        buttonGroup1.add(optAB);
        optAB.setText("A < B");

        buttonGroup1.add(optAiB);
        optAiB.setText("A <= B");

        buttonGroup1.add(optPrimo);
        optPrimo.setText("Verificar Primo");

        buttonGroup1.add(optFatorial);
        optFatorial.setText("Fatorial");

        buttonGroup1.add(optPoten);
        optPoten.setText("Potenciação");

        buttonGroup1.add(optResto);
        optResto.setText("Resto da Divisão");

        buttonGroup1.add(optBtoA);
        optBtoA.setText("B to A");

        buttonGroup1.add(optZerar);
        optZerar.setText("Zerar Registrador");

        jLabel5.setText("Registrador A:");

        jLabel6.setText("Registrador B:");

        regA.setText("(0,0)");

        regB.setText("(0,0)");

        jButton1.setText("ir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultadoReg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(entradaA)
                                        .addComponent(entradaB, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(regA)
                                            .addComponent(regB)))))
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(optSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optSomaP, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(optSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optAB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optAiB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optPrimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optFatorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optPoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optResto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optBtoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optZerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultadoReg)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regA)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entradaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(optSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optSomaP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optAB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optAiB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optPrimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optFatorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optPoten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optResto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optBtoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optZerar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resultadoReg)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[] numA;
        int[] numB;
        int[] aux;
        int aux2;
        
        int a = Integer.valueOf(entradaA.getText());
        int b = Integer.valueOf(entradaB.getText());
        
        numA = principal.iniciaReg(a);
        numB = principal.iniciaReg(b);
        
        if(optSoma.isSelected()){
            aux = principal.somaReg(numA,numB);
            if(aux[0] == 0) resultado.setText(String.valueOf(aux[1]));
                else resultado.setText("- "+String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");
        }
        else if(optSomaP.isSelected()){
            aux = principal.somaRegP(numA,numB);
            if(aux[0] == 0) resultado.setText(String.valueOf(aux[1]));
                else resultado.setText("- "+String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");
        }
        else if(optSub.isSelected()){
            aux = principal.subReg(numA,numB);
            if(aux[0] == 0) resultado.setText(String.valueOf(aux[1]));
                else resultado.setText("- "+String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");
        }
//        else if(optAB.isEnabled())
//            resultado.setText(String.valueOf(metodos.subReg(numA,numB)));            
        else if(optAiB.isSelected())
            if(principal.compReg(numA,numB) == 0) resultado.setText("A >= B");
            else resultado.setText("A < B");
        else if(optPrimo.isSelected())
            if(principal.primoReg(numA) == 0) 
                resultado.setText("É primo");
            else resultado.setText("Não é primo");
        else if(optFatorial.isSelected()){
            aux = principal.fatReg(numA);
            resultado.setText(String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");
        }
        else if(optPoten.isSelected()){
            aux = principal.potenReg(numA,numB);
            if(aux[0] == 0) resultado.setText(String.valueOf(aux[1]));
                else resultado.setText("- "+String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");
        }
        else if(optResto.isSelected()){
            aux = principal.restoDivReg(numA,numB);
            if(aux[0] == 0) resultado.setText(String.valueOf(aux[1]));
                else resultado.setText("- "+String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");            
        }
        else if(optBtoA.isSelected()){
            aux = principal.BtoA(numA,numB);
            resultado.setText(String.valueOf(aux[1]));
            resultadoReg.setText("("+String.valueOf(aux[0])+","+String.valueOf(aux[1])+")");            
        }
            
        else if(optZerar.isSelected()){
            resultado.setText(String.valueOf(principal.zerarReg(numA)));
            
            resultado.setText(String.valueOf(principal.zerarReg(numB)));
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void entradaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaAActionPerformed

    private void entradaAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaAFocusLost
        regA.setText("("+String.valueOf(principal.iniciaReg(Integer.valueOf(entradaA.getText()))[0])+","+String.valueOf(principal.iniciaReg(Integer.valueOf(entradaA.getText()))[1])+")");
    }//GEN-LAST:event_entradaAFocusLost

    private void entradaBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaBFocusLost
        regB.setText("("+String.valueOf(principal.iniciaReg(Integer.valueOf(entradaB.getText()))[0])+","+String.valueOf(principal.iniciaReg(Integer.valueOf(entradaB.getText()))[1])+")");
    }//GEN-LAST:event_entradaBFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entradaA;
    private javax.swing.JTextField entradaB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton optAB;
    private javax.swing.JRadioButton optAiB;
    private javax.swing.JRadioButton optBtoA;
    private javax.swing.JRadioButton optFatorial;
    private javax.swing.JRadioButton optPoten;
    private javax.swing.JRadioButton optPrimo;
    private javax.swing.JRadioButton optResto;
    private javax.swing.JRadioButton optSoma;
    private javax.swing.JRadioButton optSomaP;
    private javax.swing.JRadioButton optSub;
    private javax.swing.JRadioButton optZerar;
    private javax.swing.JLabel regA;
    private javax.swing.JLabel regB;
    private javax.swing.JLabel resultado;
    private javax.swing.JLabel resultadoReg;
    // End of variables declaration//GEN-END:variables
}
